# wallpaper {
#     monitor = DP-3
#     path = ~/Downloads/baikenColor.jpg
#     fit_mode = cover
# }
#
# wallpaper {
#     monitor = DP-2
#     path = ~/Downloads/baikenColorREd.jpg
#     fit_mode = cover
# }

# splash = false
wallpaper {
    monitor = 
    path = ~/Downloads/rubberDuck.jpg
    fit_mode = cover
}
